"""Response-surface figures: pressure against configuration, not verdicts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "results" / "v8a"
FIG = ROOT / "figures" / "v8a"

PALETTE = {"blue": "#2a78d6", "orange": "#eb6834", "aqua": "#1baf7a",
           "yellow": "#eda100", "magenta": "#e87ba4", "violet": "#4a3aa7"}
INK = {"primary": "#0b0b0b", "secondary": "#52514e", "muted": "#898781",
       "grid": "#e1e0d9", "axis": "#c3c2b7"}
MOD_COLOR = {"ubi": PALETTE["violet"], "cash_t": PALETTE["blue"],
             "voucher": PALETTE["yellow"], "clt": PALETTE["aqua"]}
MOD_LABEL = {"ubi": "UBI", "cash_t": "Targeted cash",
             "voucher": "Food voucher", "clt": "CLT"}
COAL_COLOR = {"D": PALETTE["yellow"], "C+D": PALETTE["aqua"],
              "B+C+D": PALETTE["blue"], "all": PALETTE["orange"]}
COAL_LABEL = {"D": "D only", "C+D": "C and D", "B+C+D": "B, C and D",
              "all": "All four"}


def style() -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    plt.rcParams.update({
        "figure.dpi": 300, "savefig.dpi": 300, "font.size": 10,
        "axes.titlesize": 12, "axes.labelsize": 10.5, "legend.fontsize": 9,
        "axes.edgecolor": INK["axis"], "xtick.color": INK["muted"],
        "ytick.color": INK["muted"], "grid.color": INK["grid"],
        "grid.linewidth": 0.6, "grid.linestyle": "-",
        "savefig.bbox": "tight", "legend.frameon": False,
        "figure.facecolor": "white", "axes.facecolor": "white",
    })


def _finish(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path.with_suffix(".png"))
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)
    print(f"  wrote {path.name}.png/.pdf")


def _series(report, section, key, field):
    us = report["u_grid"]
    return us, [report[section][key][f"{u:g}"][field] for u in us]


def _mark_defaults(ax, report, section, key, field, color, scale: float = 100.0):
    """Ring the points where a bloc has defaulted.

    A reader comparing pressure across configurations needs to know which
    points describe a world that is still whole. It is annotation, not a
    threshold: nothing is excluded or judged by it.

    `scale` must match the scaling the line was drawn with, or the rings float
    away from the curve they belong to.
    """
    us, ys = _series(report, section, key, field)
    _, defaults = _series(report, section, key, "insolvent_blocs")
    xs = [u for u, d in zip(us, defaults) if d > 0]
    marks = [scale * y for y, d in zip(ys, defaults) if d > 0]
    if xs:
        ax.scatter(xs, marks, s=52, facecolors="none", edgecolors=color,
                   linewidths=1.6, zorder=5)


def fig_modality(report, out: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(16.0, 4.4))
    for m in MOD_LABEL:
        us, pk = _series(report, "by_modality", m, "inflation_peak")
        axes[0].plot(us, [100 * v for v in pk], color=MOD_COLOR[m],
                     label=MOD_LABEL[m], linewidth=1.8, marker="o", markersize=3.5)
        _mark_defaults(axes[0], report, "by_modality", m, "inflation_peak", MOD_COLOR[m])

        _, gp = _series(report, "by_modality", m, "gap_max")
        axes[1].plot(us, [100 * v for v in gp], color=MOD_COLOR[m],
                     linewidth=1.8, marker="o", markersize=3.5)
        _mark_defaults(axes[1], report, "by_modality", m, "gap_max", MOD_COLOR[m])

        per = [report["by_modality"][m][f"{u:g}"]["inflation_peak_per_u"] for u in us]
        axes[2].plot([u for u, v in zip(us, per) if v is not None],
                     [v for v in per if v is not None],
                     color=MOD_COLOR[m], linewidth=1.8, marker="o", markersize=3.5)

    axes[0].set_ylabel("Peak world inflation (% per year)")
    axes[0].set_title("Pressure on world prices", color=INK["primary"])
    axes[0].legend(loc="upper left")
    axes[1].set_ylabel("Peak world output gap (%)")
    axes[1].set_title("Pressure on world capacity", color=INK["primary"])
    axes[2].set_ylabel("Peak inflation per unit of transfer")
    axes[2].set_title("Is pressure proportional to the programme?",
                      color=INK["primary"])
    for ax in axes:
        ax.set_xlabel("Transfer size (share of GDP)")
    fig.suptitle("Pressure generated by each modality — open circles mark "
                 "configurations in which a bloc has defaulted",
                 color=INK["primary"], y=1.04)
    _finish(fig, out)


def fig_coalition(report, out: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(12.0, 4.4))
    for name in COAL_LABEL:
        us, pk = _series(report, "by_coalition", name, "inflation_peak")
        axes[0].plot(us, [100 * v for v in pk], color=COAL_COLOR[name],
                     label=COAL_LABEL[name], linewidth=1.8, marker="o", markersize=3.5)
        _mark_defaults(axes[0], report, "by_coalition", name, "inflation_peak",
                       COAL_COLOR[name])
        _, gp = _series(report, "by_coalition", name, "gap_max")
        axes[1].plot(us, [100 * v for v in gp], color=COAL_COLOR[name],
                     linewidth=1.8, marker="o", markersize=3.5)
        _mark_defaults(axes[1], report, "by_coalition", name, "gap_max",
                       COAL_COLOR[name])
    axes[0].set_ylabel("Peak world inflation (% per year)")
    axes[0].set_title("Pressure on world prices", color=INK["primary"])
    axes[0].legend(loc="upper left")
    axes[1].set_ylabel("Peak world output gap (%)")
    axes[1].set_title("Pressure on world capacity", color=INK["primary"])
    for ax in axes:
        ax.set_xlabel("Transfer size (share of GDP)")
    fig.suptitle("Pressure against how many blocs run the programme (UBI)",
                 color=INK["primary"], y=1.04)
    _finish(fig, out)


def main() -> None:
    style()
    report = json.loads((RESULTS / "response.json").read_text())
    FIG.mkdir(parents=True, exist_ok=True)
    print("generating response-surface figures...")
    fig_modality(report, FIG / "fig4_response_modality")
    fig_coalition(report, FIG / "fig5_response_coalition")


if __name__ == "__main__":
    main()
